import { NextRequest, NextResponse } from 'next/server';
import { getSteamAppDetails, validateAppId } from '../../../../utils/steamAPI';
import { generateSteamManifest, formatManifest } from '../../../../utils/manifestGenerator';
import { generateLuaScript } from '../../../utils/luaGenerator';
import { randomBytes } from 'crypto';

// Fallback in-memory storage for when Supabase is not available
const fileStorage = new Map();

export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Generate API called');
    
    const { appId, discordUserId, discordUsername } = await request.json();
    console.log(`📝 Processing request for App ID: ${appId}, User: ${discordUsername}`);

    // Validate input
    if (!validateAppId(appId)) {
      return NextResponse.json(
        { error: 'Invalid App ID' },
        { status: 400 }
      );
    }

    if (!discordUserId) {
      return NextResponse.json(
        { error: 'Discord user ID is required' },
        { status: 400 }
      );
    }

    // Fetch Steam app data
    const appData = await getSteamAppDetails(appId);
    console.log(`🎮 Fetched Steam data for: ${appData.name}`);

    // Generate files
    const manifest = generateSteamManifest(appData);
    const manifestJson = formatManifest(manifest);
    const luaScript = generateLuaScript(appData);
    console.log('📁 Generated manifest and Lua script');

    // Generate unique access key
    const accessKey = randomBytes(16).toString('hex');

    // Calculate expiration (24 hours from now)
    const expiresAt = new Date();
    expiresAt.setHours(expiresAt.getHours() + 24);

    // Store in memory storage (reliable fallback)
    const fileData = {
      id: Date.now().toString(),
      accessKey,
      discordUserId,
      discordUsername: discordUsername || null,
      steamAppId: appId,
      steamAppName: appData.name,
      manifestContent: manifestJson,
      luaContent: luaScript,
      manifestSize: manifestJson.length,
      luaSize: luaScript.length,
      expiresAt: expiresAt,
      createdAt: new Date()
    };

    fileStorage.set(accessKey, fileData);
    console.log(`💾 Stored file in memory with key: ${accessKey}`);

    // Try Supabase if available (but don't fail if it's not)
    let storedSuccessfully = false;
    try {
      // Dynamic import to avoid crashes
      const { supabase } = await import('@/lib/supabase');
      if (supabase) {
        const { createGeneratedFile } = await import('@/lib/supabase');
        const supabaseResult = await createGeneratedFile({
          accessKey,
          discordUserId,
          discordUsername: discordUsername || null,
          steamAppId: appId,
          steamAppName: appData.name,
          manifestContent: manifestJson,
          luaContent: luaScript,
          manifestSize: manifestJson.length,
          luaSize: luaScript.length,
          expiresAt: expiresAt
        });
        
        if (supabaseResult) {
          storedSuccessfully = true;
          console.log('✅ Also stored in Supabase database');
        }
      }
    } catch (supabaseError) {
      console.log('⚠️ Supabase not available, using memory storage:', supabaseError.message);
    }

    // Create Steamtools-compatible files
    const steamtoolsManifest = createSteamtoolsManifest(manifest, appData);
    const steamtoolsLua = createSteamtoolsLua(luaScript, appData);

    console.log(`🎉 Successfully generated files for ${appData.name}`);

    return NextResponse.json({
      success: true,
      accessKey: accessKey,
      downloadUrl: `/download/${accessKey}`,
      appId: appId,
      appName: appData.name,
      storage: storedSuccessfully ? 'supabase' : 'memory',
      message: storedSuccessfully ? 'Files stored in database' : 'Files stored in memory (temporary)',
      steamtoolsFiles: {
        manifest: steamtoolsManifest,
        lua: steamtoolsLua
      }
    });

  } catch (error) {
    console.error('❌ Error generating files:', error);
    return NextResponse.json(
      { error: 'Failed to generate files: ' + error.message },
      { status: 500 }
    );
  }
}

// Export the storage for use in other routes (fallback)
export { fileStorage };

function createSteamtoolsManifest(manifest: any, appData: any) {
  return {
    format: "steamtools",
    version: "1.0",
    appid: appData.appId,
    name: appData.name,
    manifest: {
      ...manifest,
      steamtools_metadata: {
        generated_by: "Steam Manifest Generator Bot",
        generated_at: new Date().toISOString(),
        compatible_with: "Steamtools v1.0+",
        export_format: "json"
      }
    }
  };
}

function createSteamtoolsLua(luaScript: string, appData: any) {
  const steamtoolsHeader = `--[[
  Steamtools Compatible Lua Script
  Generated for: ${appData.name} (${appData.appId})
  Generated by: Steam Manifest Generator Bot
  Generated at: ${new Date().toISOString()}
  
  This script is compatible with Steamtools and can be imported
  directly into your Steamtools project.
]]\n\n`;

  return {
    format: "steamtools",
    version: "1.0",
    appid: appData.appId,
    name: appData.name,
    content: steamtoolsHeader + luaScript,
    metadata: {
      generated_by: "Steam Manifest Generator Bot",
      generated_at: new Date().toISOString(),
      compatible_with: "Steamtools v1.0+",
      language: "lua",
      encoding: "utf-8"
    }
  };
}